// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoCalculateCostController from "./auto_calculate_cost_controller"
application.register("auto-calculate-cost", AutoCalculateCostController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
